# Generated by Django 5.1.1 on 2025-05-14 15:24

import django.db.models.deletion
import epathsala.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='major12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='type12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='exam1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, unique=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, unique=True)),
                ('class_full', models.CharField(default=0, max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=20)),
                ('sub_full', models.CharField(default=0, max_length=20)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=20, unique=True)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.classes')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.AddField(
            model_name='major12',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12'),
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='epathsala/', validators=[epathsala.models.validate_pdf])),
                ('scl', models.CharField(max_length=20)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.classes')),
                ('ter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.exam1')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.CreateModel(
            name='unit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_pdf', models.FileField(upload_to='epathsala/', validators=[epathsala.models.validate_pdf])),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.classes')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.major12')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.publication')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.type12')),
                ('unit_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epathsala.unit1')),
            ],
        ),
    ]
