# Generated by Django 5.1.1 on 2025-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0002_major12_type12_customuser_staff_status_exam1_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major12',
            name='sub',
            field=models.CharField(max_length=20),
        ),
    ]
