# Generated by Django 5.1.1 on 2025-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0003_alter_major12_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='major12',
            name='num',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
