# Generated by Django 5.1.1 on 2025-05-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0005_remove_classes_major_subject_class1'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit1',
            name='class1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epathsala.classes'),
        ),
        migrations.AddField(
            model_name='unit1',
            name='sub',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='epathsala.subject'),
        ),
    ]
