# Generated by Django 5.1.1 on 2025-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0006_unit1_class1_unit1_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit1',
            name='num',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
