# Generated by Django 5.1.1 on 2025-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0007_unit1_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam1',
            name='num',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
