# Generated by Django 5.1.1 on 2025-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0008_exam1_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_full',
        ),
        migrations.RemoveField(
            model_name='exam1',
            name='major',
        ),
        migrations.RemoveField(
            model_name='exam1',
            name='num',
        ),
        migrations.RemoveField(
            model_name='exam1',
            name='type',
        ),
        migrations.RemoveField(
            model_name='major12',
            name='num',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='class1',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='class1',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='major',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='num',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='type',
        ),
    ]
