# Generated by Django 5.1.1 on 2025-05-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0009_remove_classes_class_full_remove_exam1_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type',
        ),
    ]
